services:
  movies_db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./movies_db/data:/var/lib/postgresql/data
      - ./movies_db/init:/docker-entrypoint-initdb.d 
      - ./movies_db/csv:/csv_data

  users_db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./users_db/data:/var/lib/postgresql/data
      - ./users_db/init:/docker-entrypoint-initdb.d 

  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - movies_db
      - users_db

  recommender:
    build: ./recommender
    restart: always
    ports:
      - "8000:8000"